/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthVideosIndexRouteImport } from './routes/_auth/videos/index'
import { Route as AuthVideosIdRouteImport } from './routes/_auth/videos/$id'
import { Route as AuthVideosCreateRouteImport } from './routes/_auth/videos/create'
import { Route as AuthCreativeAudioIndexRouteImport } from './routes/_auth/creative/audio/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVideosIndexRoute = AuthVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVideosIdRoute = AuthVideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVideosCreateRoute = AuthVideosCreateRouteImport.update({
  id: '/videos/create',
  path: '/videos/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreativeAudioIndexRoute = AuthCreativeAudioIndexRouteImport.update({
  id: '/creative/audio/',
  path: '/creative/audio/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/videos/$id': typeof AuthVideosIdRoute
  '/videos/create': typeof AuthVideosCreateRoute
  '/videos/': typeof AuthVideosIndexRoute
  '/creative/audio/': typeof AuthCreativeAudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/videos/$id': typeof AuthVideosIdRoute
  '/videos/create': typeof AuthVideosCreateRoute
  '/videos': typeof AuthVideosIndexRoute
  '/creative/audio': typeof AuthCreativeAudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/videos/$id': typeof AuthVideosIdRoute
  '/_auth/videos/create': typeof AuthVideosCreateRoute
  '/_auth/videos/': typeof AuthVideosIndexRoute
  '/_auth/creative/audio/': typeof AuthCreativeAudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/videos/$id' | '/videos/create' | '/videos/' | '/creative/audio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/videos/$id' | '/videos/create' | '/videos' | '/creative/audio'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/'
    | '/_auth/videos/$id'
    | '/_auth/videos/create'
    | '/_auth/videos/'
    | '/_auth/creative/audio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/videos/': {
      id: '/_auth/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof AuthVideosIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/videos/$id': {
      id: '/_auth/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof AuthVideosIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/videos/create': {
      id: '/_auth/videos/create'
      path: '/videos/create'
      fullPath: '/videos/create'
      preLoaderRoute: typeof AuthVideosCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/creative/audio/': {
      id: '/_auth/creative/audio/'
      path: '/creative/audio'
      fullPath: '/creative/audio/'
      preLoaderRoute: typeof AuthCreativeAudioIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthVideosIdRoute: typeof AuthVideosIdRoute
  AuthVideosCreateRoute: typeof AuthVideosCreateRoute
  AuthVideosIndexRoute: typeof AuthVideosIndexRoute
  AuthCreativeAudioIndexRoute: typeof AuthCreativeAudioIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthVideosIdRoute: AuthVideosIdRoute,
  AuthVideosCreateRoute: AuthVideosCreateRoute,
  AuthVideosIndexRoute: AuthVideosIndexRoute,
  AuthCreativeAudioIndexRoute: AuthCreativeAudioIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
