/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Ai: () => import('#controllers/ai-controller'),
  CreativeAudios: () => import('#controllers/creative-audios-controller'),
  Oss: () => import('#controllers/oss-controller'),
  Paraformer: () => import('#controllers/paraformer-controller'),
  Session: () => import('#controllers/session-controller'),
  VideoBreakdown: () => import('#controllers/video-breakdown-controller'),
  Videos: () => import('#controllers/videos-controller'),
  Voices: () => import('#controllers/voices-controller'),
  XhsSessions: () => import('#controllers/xhs-sessions-controller'),
}
