/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CrawlerVideoTaskTransformer from '#transformers/crawler-video-task-transformer'
import type CreativeAudioTransformer from '#transformers/creative-audio-transformer'
import type ParaformerTaskTransformer from '#transformers/paraformer-task-transformer'
import type UserPolishArticleMessageTransformer from '#transformers/user-polish-article-message-transformer'
import type UserTransformer from '#transformers/user-transformer'
import type VideoBreakdownTaskTransformer from '#transformers/video-breakdown-task-transformer'
import type VideoToVoiceTaskTransformer from '#transformers/video-to-voice-task-transformer'
import type VideoTransformer from '#transformers/video-transformer'
import type VoiceTransformer from '#transformers/voice-transformer'
import type WanxiangVideoEditTaskTransformer from '#transformers/wanxiang-video-edit-task-transformer'

export namespace Data {
  export type CrawlerVideoTask = InferData<CrawlerVideoTaskTransformer>
  export namespace CrawlerVideoTask {
    export type Variants = InferVariants<CrawlerVideoTaskTransformer>
  }
  export type CreativeAudio = InferData<CreativeAudioTransformer>
  export namespace CreativeAudio {
    export type Variants = InferVariants<CreativeAudioTransformer>
  }
  export type ParaformerTask = InferData<ParaformerTaskTransformer>
  export namespace ParaformerTask {
    export type Variants = InferVariants<ParaformerTaskTransformer>
  }
  export type UserPolishArticleMessage = InferData<UserPolishArticleMessageTransformer>
  export namespace UserPolishArticleMessage {
    export type Variants = InferVariants<UserPolishArticleMessageTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type VideoBreakdownTask = InferData<VideoBreakdownTaskTransformer>
  export namespace VideoBreakdownTask {
    export type Variants = InferVariants<VideoBreakdownTaskTransformer>
  }
  export type VideoToVoiceTask = InferData<VideoToVoiceTaskTransformer>
  export namespace VideoToVoiceTask {
    export type Variants = InferVariants<VideoToVoiceTaskTransformer>
  }
  export type Video = InferData<VideoTransformer>
  export namespace Video {
    export type Variants = InferVariants<VideoTransformer>
  }
  export type Voice = InferData<VoiceTransformer>
  export namespace Voice {
    export type Variants = InferVariants<VoiceTransformer>
  }
  export type WanxiangVideoEditTask = InferData<WanxiangVideoEditTaskTransformer>
  export namespace WanxiangVideoEditTask {
    export type Variants = InferVariants<WanxiangVideoEditTaskTransformer>
  }
}
