/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AigcBailianVideoRetalkTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'meta', 'payload', 'reason', 'result', 'status', 'taskId', 'updatedAt', 'userId'] as const
  $columns = AigcBailianVideoRetalkTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: string | null
  @column()
  declare payload: string
  @column()
  declare reason: string | null
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AigcVideoTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'meta', 'payload', 'platformTaskId', 'reason', 'status', 'type', 'updatedAt', 'userId'] as const
  $columns = AigcVideoTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: string | null
  @column()
  declare payload: string
  @column()
  declare platformTaskId: string
  @column()
  declare reason: string | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AigcVideoSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'taskId', 'type', 'updatedAt', 'userId', 'videoUrl'] as const
  $columns = AigcVideoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare taskId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare videoUrl: string
}

export class AssetImageSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'url', 'userId', 'vectorId'] as const
  $columns = AssetImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare url: string
  @column()
  declare userId: number
  @column()
  declare vectorId: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CrawlerVideoTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'platform', 'reason', 'result', 'status', 'updatedAt', 'url', 'userId', 'userInput'] as const
  $columns = CrawlerVideoTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare platform: string
  @column()
  declare reason: string | null
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: string
  @column()
  declare userInput: string
}

export class MinimaxiAudioSchema extends BaseModel {
  static $columns = ['audioUrl', 'createdAt', 'id', 'isDeleted', 'name', 'payload', 'text', 'updatedAt', 'userId'] as const
  $columns = MinimaxiAudioSchema.$columns
  @column()
  declare audioUrl: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDeleted: boolean
  @column()
  declare name: string | null
  @column()
  declare payload: string
  @column()
  declare text: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MinimaxiVoiceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'userId', 'voiceDemoUrl', 'voiceId'] as const
  $columns = MinimaxiVoiceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare voiceDemoUrl: string | null
  @column()
  declare voiceId: string
}

export class ParaformerTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'reason', 'result', 'status', 'taskId', 'updatedAt', 'userId', 'videoId'] as const
  $columns = ParaformerTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string | null
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoId: number
}

export class SystemConfigSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'group', 'id', 'key', 'updatedAt', 'value'] as const
  $columns = SystemConfigSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare group: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class UserAiArticleHistorySchema extends BaseModel {
  static $columns = ['articlesJson', 'createdAt', 'id', 'model', 'prompt', 'updatedAt', 'userId', 'videoId'] as const
  $columns = UserAiArticleHistorySchema.$columns
  @column()
  declare articlesJson: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare prompt: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare videoId: number
}

export class UserAiArticleSchema extends BaseModel {
  static $columns = ['article', 'createdAt', 'hash', 'id', 'isDeleted', 'model', 'updatedAt', 'userId', 'videoId'] as const
  $columns = UserAiArticleSchema.$columns
  @column()
  declare article: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDeleted: boolean
  @column()
  declare model: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare videoId: number
}

export class UserConfigSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'updatedAt', 'userId', 'value'] as const
  $columns = UserConfigSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'id', 'mobile', 'password', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mobile: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class VideoMinimaxiVoiceTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'minimaxiVoiceId', 'reason', 'status', 'updatedAt', 'userId', 'videoId'] as const
  $columns = VideoMinimaxiVoiceTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minimaxiVoiceId: number | null
  @column()
  declare reason: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare videoId: number
}

export class VideoToVoiceTaskSchema extends BaseModel {
  static $columns = ['audioUrl', 'config', 'createdAt', 'id', 'provider', 'reason', 'status', 'updatedAt', 'userId', 'videoId', 'voiceId'] as const
  $columns = VideoToVoiceTaskSchema.$columns
  @column()
  declare audioUrl: string | null
  @column()
  declare config: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column()
  declare reason: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoId: number
  @column()
  declare voiceId: string | null
}

export class VideoSchema extends BaseModel {
  static $columns = ['author', 'commentCount', 'coverUrl', 'createdAt', 'favoriteCount', 'fileUrl', 'id', 'likeCount', 'playCount', 'publishAt', 'shareCount', 'title', 'updatedAt', 'userId'] as const
  $columns = VideoSchema.$columns
  @column()
  declare author: string
  @column()
  declare commentCount: number
  @column()
  declare coverUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare favoriteCount: number
  @column()
  declare fileUrl: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare likeCount: number
  @column()
  declare playCount: number
  @column.dateTime()
  declare publishAt: DateTime
  @column()
  declare shareCount: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class VoiceSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'demoUrl', 'id', 'model', 'name', 'provider', 'updatedAt', 'userId', 'voiceId'] as const
  $columns = VoiceSchema.$columns
  @column()
  declare config: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare demoUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare name: string
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare voiceId: string
}

export class VolcCvProcessTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDeleted', 'payload', 'reason', 'reqKey', 'result', 'status', 'taskId', 'updatedAt', 'userId'] as const
  $columns = VolcCvProcessTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDeleted: boolean
  @column()
  declare payload: string
  @column()
  declare reason: string | null
  @column()
  declare reqKey: string
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class VolcCvProcessVideoSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDeleted', 'payload', 'updatedAt', 'userId', 'videoUrl'] as const
  $columns = VolcCvProcessVideoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDeleted: boolean
  @column()
  declare payload: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare videoUrl: string
}

export class XhsMessageSchema extends BaseModel {
  static $columns = ['content', 'contentType', 'createdAt', 'id', 'metadata', 'role', 'sessionId'] as const
  $columns = XhsMessageSchema.$columns
  @column()
  declare content: string
  @column()
  declare contentType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare role: string
  @column()
  declare sessionId: number
}

export class XhsSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastMessage', 'title', 'updatedAt', 'userId'] as const
  $columns = XhsSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastMessage: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}
