/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CrawlerVideoTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'platform', 'reason', 'result', 'status', 'updatedAt', 'url', 'userId', 'userInput'] as const
  $columns = CrawlerVideoTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare platform: string
  @column()
  declare reason: string | null
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: string
  @column()
  declare userInput: string
}

export class CreativeAudioSchema extends BaseModel {
  static $columns = ['audioUrl', 'configs', 'createdAt', 'id', 'model', 'provider', 'text', 'updatedAt', 'userId', 'voiceId'] as const
  $columns = CreativeAudioSchema.$columns
  @column()
  declare audioUrl: string
  @column()
  declare configs: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare provider: string
  @column()
  declare text: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare voiceId: string
}

export class ParaformerTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'reason', 'result', 'status', 'taskId', 'updatedAt', 'userId', 'videoId'] as const
  $columns = ParaformerTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string | null
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoId: number
}

export class UserPolishArticleMessageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'role', 'updatedAt', 'userId', 'videoId'] as const
  $columns = UserPolishArticleMessageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'id', 'mobile', 'password', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mobile: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class VideoBreakdownTaskSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'reason', 'result', 'status', 'taskId', 'updatedAt', 'userId', 'videoUrl'] as const
  $columns = VideoBreakdownTaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string | null
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoUrl: string
}

export class VideoEditMessageSchema extends BaseModel {
  static $columns = ['createdAt', 'entityId', 'id', 'message', 'role', 'taskId', 'updatedAt', 'userId'] as const
  $columns = VideoEditMessageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare role: string
  @column()
  declare taskId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class VideoToVoiceTaskSchema extends BaseModel {
  static $columns = ['audioUrl', 'config', 'createdAt', 'id', 'provider', 'reason', 'status', 'updatedAt', 'userId', 'videoId', 'voiceId'] as const
  $columns = VideoToVoiceTaskSchema.$columns
  @column()
  declare audioUrl: string | null
  @column()
  declare config: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column()
  declare reason: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoId: number
  @column()
  declare voiceId: string | null
}

export class VideoSchema extends BaseModel {
  static $columns = ['author', 'commentCount', 'coverUrl', 'createdAt', 'favoriteCount', 'fileUrl', 'id', 'likeCount', 'platform', 'playCount', 'publishAt', 'shareCount', 'title', 'updatedAt', 'userId'] as const
  $columns = VideoSchema.$columns
  @column()
  declare author: string
  @column()
  declare commentCount: number
  @column()
  declare coverUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare favoriteCount: number
  @column()
  declare fileUrl: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare likeCount: number
  @column()
  declare platform: string
  @column()
  declare playCount: number
  @column.dateTime()
  declare publishAt: DateTime
  @column()
  declare shareCount: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class VoiceSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'demoUrl', 'description', 'id', 'model', 'name', 'provider', 'updatedAt', 'userId', 'voiceId'] as const
  $columns = VoiceSchema.$columns
  @column()
  declare config: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare demoUrl: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare name: string
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare voiceId: string
}

export class WanxiangVideoEditTaskSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'entityId', 'id', 'reason', 'result', 'status', 'taskId', 'updatedAt', 'userId', 'videoUrl'] as const
  $columns = WanxiangVideoEditTaskSchema.$columns
  @column()
  declare config: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string | null
  @column()
  declare result: string | null
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare videoUrl: string | null
}
